In [2]:
import numpy as np

1D array

In [ ]:
# Create a list of numbers from 10 to 100 with a step of 10
my_list= [10,20,30,40,50,60,70,80,90,100]
arr= np.array(my_list) # Convert the list to a NumPy array
arr 

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

2D array

In [ ]:
# Create a 2D array with 2 rows and 2 columns
arr1= np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

3D array

In [ ]:
# Create a 3D array with 3 layers, 4 rows, and 4 columns
arr2= np.array([[[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]],
                [[16,17,18,19],[20,21,22,23],[24,25,26,27],[28,29,30,31]],
                [[32,33,34,35],[36,37,38,39],[40,41,42,43],[44,45,46,47]]])
arr2

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

Usage of np.zeros()

In [ ]:
# Create a 1D array of zeros with 5 elements
zeros_1d= np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

Usage of np.ones()

In [ ]:
# Create a 2D array of ones with 4 rows and 5 columns
ones_2d= np.ones((4,5))
ones_2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Usage of np.full()

In [ ]:
# Create a 3D array filled with the number 32, with 2 layers, 2 rows, and 2 columns
any_number_3d= np.full((2,2,2),32)
any_number_3d

array([[[32, 32],
        [32, 32]],

       [[32, 32],
        [32, 32]]])

use of np.zeros_like()

In [ ]:
# Create a 2D array with 3 rows and 3 columns
org_array=([[1,2,3],
           [4,5,6],
           [7,8,9]])
mask= np.zeros_like(org_array) # Create a mask of zeros with the same shape as org_array
mask

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

use of np.ones_like()

In [ ]:
# Create a mask of ones with the same shape as org_array
mask_ones= np.ones_like(org_array) 
mask_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

use of np.full_like()

In [ ]:
# Create a mask filled with the number 56, with the same shape as org_array
mask_any_num= np.full_like(org_array,56)
mask_any_num

array([[56, 56, 56],
       [56, 56, 56],
       [56, 56, 56]])

use of np.arange()

In [ ]:
# Create a 1D array of numbers from 0 to 6
arr_range1= np.arange(7)
arr_range1

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
# Create a 1D array of even numbers from 2 to 10
arr_range2= np.arange(2,11,2)
arr_range2

array([ 2,  4,  6,  8, 10])

Use of np.linspace()

In [ ]:
# Create a 1D array of numbers from 0 to 10, with 5 equally spaced values
same_distance_num= np.linspace(0,10,5)
same_distance_num

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Array Attributes

In [6]:
arr3 = np.array([[10, 20, 30],
                     [40, 50, 60]])
print(arr3.ndim)
# output: 2
# that means arr3 is a 2-dimensional array

print(arr3.shape)
# output: (2, 3) 
# that means arr3 has 2 rows and 3 columns

print(arr3.size)
# output: 6
# that means arr3 has 6 elements in total

print(arr3.dtype)
# output: int64
# that means the data type of the elements in arr3 is 64-bit integer

2
(2, 3)
6
int64
