Importing numpy library

In [1]:
import numpy as np

1D array

In [ ]:
# Create a list of numbers from 10 to 100 with a step of 10
my_list= [10,20,30,40,50,60,70,80,90,100]
arr= np.array(my_list) # Convert the list to a NumPy array
arr 

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

2D array

In [ ]:
# Create a 2D array with 2 rows and 2 columns
arr1= np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

3D array

In [ ]:
# Create a 3D array with 3 layers, 4 rows, and 4 columns
arr2= np.array([[[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]],
                [[16,17,18,19],[20,21,22,23],[24,25,26,27],[28,29,30,31]],
                [[32,33,34,35],[36,37,38,39],[40,41,42,43],[44,45,46,47]]])
arr2

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

Usage of np.zeros()

In [ ]:
# Create a 1D array of zeros with 5 elements
zeros_1d= np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

Usage of np.ones()

In [ ]:
# Create a 2D array of ones with 4 rows and 5 columns
ones_2d= np.ones((4,5))
ones_2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Usage of np.full()

In [ ]:
# Create a 3D array filled with the number 32, with 2 layers, 2 rows, and 2 columns
any_number_3d= np.full((2,2,2),32)
any_number_3d

array([[[32, 32],
        [32, 32]],

       [[32, 32],
        [32, 32]]])

use of np.zeros_like()

In [ ]:
# Create a 2D array with 3 rows and 3 columns
org_array=([[1,2,3],
           [4,5,6],
           [7,8,9]])
mask= np.zeros_like(org_array) # Create a mask of zeros with the same shape as org_array
mask

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

use of np.ones_like()

In [ ]:
# Create a mask of ones with the same shape as org_array
mask_ones= np.ones_like(org_array) 
mask_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

use of np.full_like()

In [ ]:
# Create a mask filled with the number 56, with the same shape as org_array
mask_any_num= np.full_like(org_array,56)
mask_any_num

array([[56, 56, 56],
       [56, 56, 56],
       [56, 56, 56]])

use of np.arange()

In [ ]:
# Create a 1D array of numbers from 0 to 6
arr_range1= np.arange(7)
arr_range1

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
# Create a 1D array of even numbers from 2 to 10
arr_range2= np.arange(2,11,2)
arr_range2

array([ 2,  4,  6,  8, 10])

Use of np.linspace()

In [ ]:
# Create a 1D array of numbers from 0 to 10, with 5 equally spaced values
same_distance_num= np.linspace(0,10,5)
same_distance_num

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Array Attributes

In [6]:
arr3 = np.array([[10, 20, 30],
                     [40, 50, 60]])
print(arr3.ndim)
# output: 2
# that means arr3 is a 2-dimensional array

print(arr3.shape)
# output: (2, 3) 
# that means arr3 has 2 rows and 3 columns

print(arr3.size)
# output: 6
# that means arr3 has 6 elements in total

print(arr3.dtype)
# output: int64
# that means the data type of the elements in arr3 is 64-bit integer

2
(2, 3)
6
int64


Array Manipulation

In [ ]:
# --------------------------------------------------- Reshaping Arrays ---------------------------------------------------

# Create a 1D array of numbers from 1 to 12
arr_1d = np.arange(1, 13)
print("Original 1D:", arr_1d) # [ 1  2  3  4  5  6  7  8  9 10 11 12]

# Reshape it into a 2D array with 3 rows and 4 columns (3 x 4 = 12)
arr_2d = np.reshape(arr_1d, (3, 4))  # Or arr_1d.reshape(3, 4) would also work

print("\nReshaped to 3x4:\n", arr_2d)

Original 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# -- --------------------------------------------------- Flattening Arrays ---------------------------------------------------

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

# use flatten to convert the 2D array into a 1D array 
flat_arr = matrix.flatten()
print("Flattened:", flat_arr) # Output: [1 2 3 4 5 6]

Flattened: [1 2 3 4 5 6]


In [ ]:
# --------------------------------------------------- Expanding Dimensions ---------------------------------------------------

arr4 = np.array([10, 20, 30])
print("Original Shape:", arr4.shape) # Output: (3,) -> This is a 1D array

# Expand dimensions along axis 0 (row-wise)
expanded_row = np.expand_dims(arr4, axis=0) # This will add a new axis at the beginning, making it a 2D array with 1 row and 3 columns
print("\nExpanded (Row-wise):", expanded_row) 
print("New Shape:", expanded_row.shape)       # (1, 3) -> This is now a 2D array

# Expand dimensions along axis 1 (column-wise)
expanded_col = np.expand_dims(arr4, axis=1) # This will add a new axis at the end, making it a 2D array with 3 rows and 1 column
print("\nExpanded (Column-wise):\n", expanded_col) 

print("New Shape:", expanded_col.shape)       # (3, 1)

Original Shape: (3,)

Expanded (Row-wise): [[10 20 30]]
New Shape: (1, 3)

Expanded (Column-wise):
 [[10]
 [20]
 [30]]
New Shape: (3, 1)


In [5]:
# --------------------------------------------------- Squeezing Arrays ---------------------------------------------------
arr_3d = np.array([[[10,20,30],
                    [20,40,50],
                    [30,60,70]]])

print("Original Shape:", arr_3d.shape) 

# Using np.squeeze() to drop unnecessary dimensions of size 1 
# (e.g., converting shape from (1, 3, 3) to (3, 3)) without changing the data.
squeezed_arr = np.squeeze(arr_3d)
print("\nSqueezed Array:", squeezed_arr)
print("New Shape:", squeezed_arr.shape)  

Original Shape: (1, 3, 3)

Squeezed Array: [[10 20 30]
 [20 40 50]
 [30 60 70]]
New Shape: (3, 3)


In [2]:
# --------------------------------------------------- Changing Data Types ---------------------------------------------------

# defaultly it will be created as float64
arr_float64 = np.array([1.5, 2.7, 3.9])
print("Original dtype:", arr_float64.dtype) # output: float64

# to save memory, convert to float32
arr_float32 = arr_float64.astype('float32')
print("New dtype:", arr_float32.dtype)      # output: float32

# to save even more memory, convert to float16 (but be aware of precision loss)
arr_float16 = arr_float64.astype('float16')
print("New dtype (float16):", arr_float16.dtype) # output: float16

# We can also convert to integers, but this will truncate the decimal part
arr_int = arr_float64.astype('int')
print("New dtype (int):", arr_int.dtype) # output: int64

Original dtype: float64
New dtype: float32
New dtype (float16): float16
New dtype (int): int64


In [3]:
# --------------------------------------------------- Concatenating Arrays ---------------------------------------------------

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# axis 0 (row-wise or vertically) concatenation
concat_row = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along rows:\n", concat_row)

# axis 1 (column-wise or horizontally) concatenation
concat_col = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated along columns:\n", concat_col)


Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]


In [8]:
# these are just shortcuts for concatenation along specific axes.

# it will stack arr1 and arr2 vertically (row-wise), resulting in a 2D array with 4 rows and 2 columns
v_stacked = np.vstack((arr1, arr2))
print("Vstack:\n", v_stacked)


# This will concatenate arr1 and arr2 horizontally (column-wise). 
# The result will be a 2D array of shape (2, 4).
h_stacked = np.hstack((arr1, arr2))
print("\nHstack:", h_stacked)

print("\nVstack shape:", v_stacked.shape) 
print("Hstack shape:", h_stacked.shape) 

Vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Hstack: [[1 2 5 6]
 [3 4 7 8]]

Vstack shape: (4, 2)
Hstack shape: (2, 4)


In [9]:
# --------------------------------------------------- Splitting Arrays ---------------------------------------------------

# create a dataset of numbers from 1 to 9
dataset = np.arange(1, 10)
print("Original Dataset:", dataset)

# create 3 equal parts of the array (each part will have 3 elements since 9/3=3)
split_arr = np.split(dataset, 3)
print("\nSplit into 3 equal parts:")
print("Part 1:", split_arr[0]) # Output: [1 2 3]
print("Part 2:", split_arr[1]) # Output: [4 5 6]
print("Part 3:", split_arr[2]) # Output: [7 8 9]

# Split at specific indices (e.g., Train and Test)
# Suppose the first 6 elements are for Training and the rest for Testing
train_set, test_set = np.split(dataset, [6])
print("\nTrain Set:", train_set) # Output: [1 2 3 4 5 6]
print("Test Set:", test_set)   # Output: [7 8 9]

Original Dataset: [1 2 3 4 5 6 7 8 9]

Split into 3 equal parts:
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]

Train Set: [1 2 3 4 5 6]
Test Set: [7 8 9]
