In [1]:
import numpy as np

1D array

In [10]:
my_list= [10,20,30,40,50,60,70,80,90,100]
arr= np.array(my_list)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

2D array

In [9]:
arr1= np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

3D array

In [8]:
arr2= np.array([[[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]],
                [[16,17,18,19],[20,21,22,23],[24,25,26,27],[28,29,30,31]],
                [[32,33,34,35],[36,37,38,39],[40,41,42,43],[44,45,46,47]]])
arr2

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

Usage of np.zeros()

In [7]:
zeros_1d= np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

Usage of np.ones()

In [6]:
ones_2d= np.ones((4,5))
ones_2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Usage of np.full()

In [5]:
any_number_3d= np.full((2,2,2),32)
any_number_3d

array([[[32, 32],
        [32, 32]],

       [[32, 32],
        [32, 32]]])

use of np.zeros_like()

In [4]:
org_array=([[1,2,3],
           [4,5,6],
           [7,8,9]])
mask= np.zeros_like(org_array)
mask

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

use of np.ones_like()

In [21]:
mask_ones= np.ones_like(org_array)
mask_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

use of np.full_like()

In [22]:
mask_any_num= np.full_like(org_array,56)
mask_any_num

array([[56, 56, 56],
       [56, 56, 56],
       [56, 56, 56]])

use of np.arange()

In [3]:
arr_range1= np.arange(7)
arr_range1

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
arr_range2= np.arange(2,11,2)
arr_range2

array([ 2,  4,  6,  8, 10])

Use of np.linspace()

In [2]:
same_distance_num= np.linspace(0,10,5)
same_distance_num

array([ 0. ,  2.5,  5. ,  7.5, 10. ])